name: Build and test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read


jobs:
  test:
    name: Build and test app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: make install

      - name: Run linting and check formatting
        run: |
          make lint
          make fmt-check

      - name: Run pytest
        run: make test
